const descriptions={rizon:['Dual Rizon4s','Two single-arm instances, one coordinated task.'],marvin:['Marvin Pro M6','A native dual-arm embodiment using the shared task interface.'],aloha:['ALOHA','Native dual arms with embodiment-specific TCP calibration.'],franka:['Franka Panda','Two Panda instances executing the same sorting logic.'],arx_x5:['ARX X5','A composed dual-arm layout with calibrated grasp frames.'],piper:['Piper','The same task, with Piper kinematics and gripper geometry.'],ur5_wsg:['UR5 + WSG','UR5 arms paired with WSG parallel grippers.']};
const robotVideo=document.querySelector('#robot-video');
document.querySelectorAll('[data-robot]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.robot;document.querySelectorAll('[data-robot]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});robotVideo.pause();robotVideo.poster=`${key}.jpg`;robotVideo.src=`${key}.mp4`;robotVideo.setAttribute('aria-label',descriptions[key][0]+' RGB block sorting demonstration');document.querySelector('#robot-title').textContent=descriptions[key][0];document.querySelector('#robot-detail').textContent=descriptions[key][1];robotVideo.load();}));
document.querySelector('#robot-speed').addEventListener('change',e=>robotVideo.playbackRate=Number(e.target.value));robotVideo.addEventListener('loadedmetadata',()=>robotVideo.playbackRate=Number(document.querySelector('#robot-speed').value));
const hero=document.querySelector('#hero-video'),toggle=document.querySelector('#hero-toggle');
function heroState(){toggle.textContent=hero.paused?'Play':'Pause';toggle.setAttribute('aria-label',hero.paused?'Play hero video':'Pause hero video')}
toggle.addEventListener('click',()=>{if(hero.paused)hero.play().catch(()=>{});else hero.pause()});hero.addEventListener('play',heroState);hero.addEventListener('pause',heroState);if(matchMedia('(prefers-reduced-motion: reduce)').matches){hero.autoplay=false;hero.pause();heroState()}
const taskData={sorting:{media:'marvin',robot:'MARVIN PRO M6 / DUAL ARM',kicker:'COORDINATED MANIPULATION',title:'Sort by color.\nCoordinate two arms.',description:'Pick, lift, and place three colored blocks into an ordered arrangement. The same task class runs on seven embodiment configurations.',primitives:['grasp','move_relative','place','return_home'],success:'Final object placement and RGB ordering are checked after execution.'},rack:{media:'rack',robot:'RIZON4S / SINGLE ARM',kicker:'GEOMETRY-DRIVEN PLACEMENT',title:'Pick a rack.\nPlace it in its holder.',description:'Resolve a grasp from annotated contact points, then use the asset’s functional frame to place the rack into its matching holder.',primitives:['grasp','move_relative','place','open_gripper'],success:'The rack must reach the holder’s target region after physical placement.'},pouring:{media:'pouring',robot:'MARVIN PRO M6 / DUAL ARM',kicker:'SEQUENCED OBJECT INTERACTION',title:'Grasp, pour,\nand return.',description:'Coordinate glassware handling, horizontal side grasping, a pouring motion, and return-to-rack placement with simulated liquid particles.',primitives:['grasp','move_relative','place','return_home'],success:'Liquid transfer and return placement are checked in the recorded pouring workflow.'}};
const taskVideo=document.querySelector('#task-video');document.querySelectorAll('[data-task]').forEach(b=>b.addEventListener('click',()=>{const d=taskData[b.dataset.task];document.querySelectorAll('[data-task]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});taskVideo.pause();taskVideo.poster=`${d.media}.jpg`;taskVideo.src=`${d.media}.mp4`;taskVideo.setAttribute('aria-label',d.title.replace('\n',' '));taskVideo.load();for(const k of ['robot','kicker','description','success'])document.querySelector('#task-'+k).textContent=d[k];const title=document.querySelector('#task-title');title.replaceChildren();d.title.split('\n').forEach((t,i)=>{if(i)title.append(document.createElement('br'));title.append(document.createTextNode(t))});document.querySelector('#task-primitives').replaceChildren(...d.primitives.map(p=>{const c=document.createElement('code');c.textContent=p;return c}))}));
const navVideo=document.querySelector('#navigation-video');document.querySelectorAll('[data-time]').forEach(b=>b.addEventListener('click',()=>{const seekAndPlay=()=>{navVideo.currentTime=Number(b.dataset.time);navVideo.play().catch(()=>{})};if(navVideo.readyState>=1)seekAndPlay();else{navVideo.addEventListener('loadedmetadata',seekAndPlay,{once:true});navVideo.load()}}));document.querySelector('#navigation-speed').addEventListener('change',e=>navVideo.playbackRate=Number(e.target.value));navVideo.addEventListener('timeupdate',()=>{const buttons=[...document.querySelectorAll('[data-time]')];buttons.forEach((b,i)=>b.classList.toggle('active',navVideo.currentTime>=Number(b.dataset.time)&&(!buttons[i+1]||navVideo.currentTime<Number(buttons[i+1].dataset.time))))});
// Pause competing recordings without changing the user's selected playback speed.
document.querySelectorAll('video:not(#hero-video)').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(other=>{if(other!==v)other.pause()})));
